# Generated by Django 2.2.6 on 2019-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fibonaccis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fib_result', models.TextField(max_length=65535)),
                ('exe_time', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'fib_table',
            },
        ),
    ]
